from enum import Enum


class FirewallPolicyIPv4NamedProtocolName(str, Enum):
    AH = "ah"
    AX_25 = "ax.25"
    DCCP = "dccp"
    DDP = "ddp"
    EGP = "egp"
    EIGRP = "eigrp"
    ENCAP = "encap"
    ESP = "esp"
    ETHERIP = "etherip"
    FC = "fc"
    GGP = "ggp"
    GRE = "gre"
    HIP = "hip"
    HMP = "hmp"
    ICMP = "icmp"
    ICMPV6 = "icmpv6"
    IDPR_CMTP = "idpr-cmtp"
    IDRP = "idrp"
    IGMP = "igmp"
    IGP = "igp"
    IP = "ip"
    IPCOMP = "ipcomp"
    IPENCAP = "ipencap"
    IPIP = "ipip"
    IPV6 = "ipv6"
    IPV6_FRAG = "ipv6-frag"
    IPV6_NONXT = "ipv6-nonxt"
    IPV6_OPTS = "ipv6-opts"
    IPV6_ROUTE = "ipv6-route"
    ISIS = "isis"
    ISO_TP4 = "iso-tp4"
    L2TP = "l2tp"
    MANET = "manet"
    MOBILITY_HEADER = "mobility-header"
    MPLS_IN_IP = "mpls-in-ip"
    OSPF = "ospf"
    PIM = "pim"
    PUP = "pup"
    RDP = "rdp"
    ROHC = "rohc"
    RSPF = "rspf"
    RSVP = "rsvp"
    SCTP = "sctp"
    SHIM6 = "shim6"
    SKIP = "skip"
    ST = "st"
    TCP = "tcp"
    TCP_UDP = "tcp_udp"
    UDP = "udp"
    UDPLITE = "udplite"
    VMTP = "vmtp"
    VRRP = "vrrp"
    WESP = "wesp"
    XNS_IDP = "xns-idp"
    XTP = "xtp"

    def __str__(self) -> str:
        return str(self.value)
