from enum import Enum


class IntegrationFirewallPolicyIpv6NamedProtocolIcmpv6DtoTypenameFilter(str, Enum):
    ADDRESS_UNREACHABLE = "ADDRESS_UNREACHABLE"
    BAD_HEADER = "BAD_HEADER"
    BEYOND_SCOPE = "BEYOND_SCOPE"
    COMMUNICATION_PROHIBITED = "COMMUNICATION_PROHIBITED"
    DESTINATION_UNREACHABLE = "DESTINATION_UNREACHABLE"
    ECHO_REPLY = "ECHO_REPLY"
    ECHO_REQUEST = "ECHO_REQUEST"
    FAILED_POLICY = "FAILED_POLICY"
    NEIGHBOR_ADVERTISEMENT = "NEIGHBOR_ADVERTISEMENT"
    NEIGHBOR_SOLICITATION = "NEIGHBOR_SOLICITATION"
    NO_ROUTE = "NO_ROUTE"
    PACKET_TOO_BIG = "PACKET_TOO_BIG"
    PARAMETER_PROBLEM = "PARAMETER_PROBLEM"
    PORT_UNREACHABLE = "PORT_UNREACHABLE"
    REDIRECT = "REDIRECT"
    REJECT_ROUTE = "REJECT_ROUTE"
    ROUTER_ADVERTISEMENT = "ROUTER_ADVERTISEMENT"
    ROUTER_SOLICITATION = "ROUTER_SOLICITATION"
    TIME_EXCEEDED = "TIME_EXCEEDED"
    TTL_ZERO_DURING_REASSEMBLY = "TTL_ZERO_DURING_REASSEMBLY"
    TTL_ZERO_DURING_TRANSIT = "TTL_ZERO_DURING_TRANSIT"
    UNKNOWN_HEADER_TYPE = "UNKNOWN_HEADER_TYPE"
    UNKNOWN_OPTION = "UNKNOWN_OPTION"

    def __str__(self) -> str:
        return str(self.value)
