from enum import Enum


class IntegrationWifiMdnsProxyPredefinedServiceDtoName(str, Enum):
    AMAZON_DEVICES = "AMAZON_DEVICES"
    ANDROID_TV_REMOTE = "ANDROID_TV_REMOTE"
    APPLE_AIR_DROP = "APPLE_AIR_DROP"
    APPLE_AIR_PLAY = "APPLE_AIR_PLAY"
    APPLE_FILE_SHARING = "APPLE_FILE_SHARING"
    APPLE_ICHAT = "APPLE_ICHAT"
    APPLE_ITUNES = "APPLE_ITUNES"
    AQARA = "AQARA"
    BOSE = "BOSE"
    DNS_SERVICE_DISCOVERY = "DNS_SERVICE_DISCOVERY"
    FTP_SERVERS = "FTP_SERVERS"
    GOOGLE_CHROMECAST = "GOOGLE_CHROMECAST"
    HOMEKIT = "HOMEKIT"
    MATTER_NETWORK = "MATTER_NETWORK"
    PHILIPS_HUE = "PHILIPS_HUE"
    PRINTERS = "PRINTERS"
    ROKU = "ROKU"
    SCANNERS = "SCANNERS"
    SHELLY = "SHELLY"
    SONOS = "SONOS"
    SPOTIFY_CONNECT = "SPOTIFY_CONNECT"
    SSH_SERVERS = "SSH_SERVERS"
    TIME_CAPSULE = "TIME_CAPSULE"
    WEB_SERVERS = "WEB_SERVERS"
    WINDOWS_FILE_SHARING_SAMBA = "WINDOWS_FILE_SHARING_SAMBA"

    def __str__(self) -> str:
        return str(self.value)
