from enum import Enum


class IntegrationWifiRadiusMacAuthenticationConfigurationDtoMacAddressFormat(str, Enum):
    LOWERCASE_COLON_SEPARATED = "LOWERCASE_COLON_SEPARATED"
    LOWERCASE_DASH_SEPARATED = "LOWERCASE_DASH_SEPARATED"
    LOWERCASE_NOT_SEPARATED = "LOWERCASE_NOT_SEPARATED"
    UPPERCASE_COLON_SEPARATED = "UPPERCASE_COLON_SEPARATED"
    UPPERCASE_DASH_SEPARATED = "UPPERCASE_DASH_SEPARATED"
    UPPERCASE_NOT_SEPARATED = "UPPERCASE_NOT_SEPARATED"

    def __str__(self) -> str:
        return str(self.value)
